//Teste de Requisições REST - Produtos
@baseURL = https://backend-cadastro-produtos.vercel.app/api
@id = 637e457558ed3c5de6c81b51
@nome_produto = Processador AMD Ryzen 9 
###
// GET - Lista todos os produtos
GET {{baseURL}}/produtos
Content-Type: application/json

###
// GET - Lista apenas um produto pelo id
GET {{baseURL}}/produtos/id/{{id}}
Content-Type: application/json

###
// GET - Lista apenas um produto pelo nome do produto
GET {{baseURL}}/produtos/nome_produto/{{nome_produto}}
Content-Type: application/json

###
// POST - Inclui um novo produto
POST {{baseURL}}/produtos
Content-Type: application/json

{
   "codigo_produto": 1,
   "nome_produto": "Processador AMD Ryzen 9",
   "descricao_produto": "Processador Ryzen 9 7900x",
   "valor_produto": 2500.00,
   "categoria": "Processadores"
}

### 
// DELETE - Apaga um produto através do id informado
DELETE {{baseURL}}/produtos/{{id}}
Content-Type: application/json

###
// PUT - Altera um produto pelo ID
PUT {{baseURL}}/produtos
Content-Type: application/json

{
    "_id": "637e457558ed3c5de6c81b51",
    "codigo_produto": 1,
    "nome_produto": "Placa Mãe Gigabite Z540",
    "descricao_produto": "Placa Mãe AM4",
    "valor_produto": 2000.00,
    "categoria": "Placa mãe"
  }



